package com.example.anonymous.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import bc.juhaohd.com.bean.GdAttrBean;
import bc.juhaohd.com.bean.GdAttrBeanList;
import bc.juhaohd.com.bean.GdGoodsBean;
import bc.juhaohd.com.bean.GdGoodsDetial;

import com.example.anonymous.greendao.GdAttrBeanDao;
import com.example.anonymous.greendao.GdAttrBeanListDao;
import com.example.anonymous.greendao.GdGoodsBeanDao;
import com.example.anonymous.greendao.GdGoodsDetialDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gdAttrBeanDaoConfig;
    private final DaoConfig gdAttrBeanListDaoConfig;
    private final DaoConfig gdGoodsBeanDaoConfig;
    private final DaoConfig gdGoodsDetialDaoConfig;

    private final GdAttrBeanDao gdAttrBeanDao;
    private final GdAttrBeanListDao gdAttrBeanListDao;
    private final GdGoodsBeanDao gdGoodsBeanDao;
    private final GdGoodsDetialDao gdGoodsDetialDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gdAttrBeanDaoConfig = daoConfigMap.get(GdAttrBeanDao.class).clone();
        gdAttrBeanDaoConfig.initIdentityScope(type);

        gdAttrBeanListDaoConfig = daoConfigMap.get(GdAttrBeanListDao.class).clone();
        gdAttrBeanListDaoConfig.initIdentityScope(type);

        gdGoodsBeanDaoConfig = daoConfigMap.get(GdGoodsBeanDao.class).clone();
        gdGoodsBeanDaoConfig.initIdentityScope(type);

        gdGoodsDetialDaoConfig = daoConfigMap.get(GdGoodsDetialDao.class).clone();
        gdGoodsDetialDaoConfig.initIdentityScope(type);

        gdAttrBeanDao = new GdAttrBeanDao(gdAttrBeanDaoConfig, this);
        gdAttrBeanListDao = new GdAttrBeanListDao(gdAttrBeanListDaoConfig, this);
        gdGoodsBeanDao = new GdGoodsBeanDao(gdGoodsBeanDaoConfig, this);
        gdGoodsDetialDao = new GdGoodsDetialDao(gdGoodsDetialDaoConfig, this);

        registerDao(GdAttrBean.class, gdAttrBeanDao);
        registerDao(GdAttrBeanList.class, gdAttrBeanListDao);
        registerDao(GdGoodsBean.class, gdGoodsBeanDao);
        registerDao(GdGoodsDetial.class, gdGoodsDetialDao);
    }
    
    public void clear() {
        gdAttrBeanDaoConfig.getIdentityScope().clear();
        gdAttrBeanListDaoConfig.getIdentityScope().clear();
        gdGoodsBeanDaoConfig.getIdentityScope().clear();
        gdGoodsDetialDaoConfig.getIdentityScope().clear();
    }

    public GdAttrBeanDao getGdAttrBeanDao() {
        return gdAttrBeanDao;
    }

    public GdAttrBeanListDao getGdAttrBeanListDao() {
        return gdAttrBeanListDao;
    }

    public GdGoodsBeanDao getGdGoodsBeanDao() {
        return gdGoodsBeanDao;
    }

    public GdGoodsDetialDao getGdGoodsDetialDao() {
        return gdGoodsDetialDao;
    }

}
